# esse é um arquivo de configurações
# aqui colocamos os serviços e as coisas que vão ter no nosso servidor

# versão do arquivo de configuração
version: "3"

# serviços rodando
services:
  www:
    build: .
    restart: always
    ports:
      - '8000:80'
    volumes:
      - ./www:/var/www/html
    networks:
      - default
  db:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: meudb
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - default

# volumes de dados (local para armazenar os dados)
volumes:
  db_data: